=begin
#API v1.0.1

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for PipelinePublisher::StreamMetricsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StreamMetricsApi' do
  before do
    # run before each test
    @instance = PipelinePublisher::StreamMetricsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StreamMetricsApi' do
    it 'should create an instance of StreamMetricsApi' do
      expect(@instance).to be_instance_of(PipelinePublisher::StreamMetricsApi)
    end
  end

  # unit tests for stream_metrics_get
  # Fetches metrics about the stream
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :count_since_timestamp ISO 8601 compliant timestamp to perform message count calculations from. Example: 2018-04-12T23:54:57.595Z
  # @return [nil]
  describe 'stream_metrics_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
